@extends('layouts.app')
@section('title','Command center')
@section('eyebrow','Today’s opportunity pulse')
@section('content')
<div class="stat-grid">
@foreach([['campaigns','bi-bullseye','Campaigns'],['leads','bi-buildings','Total leads'],['without_website','bi-globe2','No website'],['hot','bi-fire','Hot leads'],['today_followups','bi-calendar2-check','Due today']] as [$key,$icon,$label])
<div class="stat"><div class="icon"><i class="bi {{ $icon }}"></i></div><strong>{{ number_format($stats[$key]) }}</strong><span>{{ $label }}</span></div>
@endforeach
</div>
<div class="row g-4">
<div class="col-xl-7"><section class="panel h-100"><div class="panel-head"><h2>Recent campaigns</h2><a href="{{ route('campaigns.index') }}" class="small">View all</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Campaign</th><th>Status</th><th>Progress</th><th>Leads</th></tr></thead><tbody>@forelse($recentCampaigns as $campaign)<tr><td><a class="business-name" href="{{ route('campaigns.show',$campaign) }}">{{ $campaign->title }}</a><div class="muted">{{ $campaign->city }} · {{ $campaign->business_category }}</div></td><td><span class="badge badge-soft">{{ ucfirst($campaign->status) }}</span></td><td style="min-width:130px"><div class="progress"><div class="progress-bar bg-success" style="width:{{$campaign->progress_percentage}}%"></div></div><small class="muted">{{$campaign->progress_percentage}}%</small></td><td>{{$campaign->total_saved}}</td></tr>@empty<tr><td colspan="4" class="text-center py-5 text-secondary">No campaigns yet. Create a focused local search to begin.</td></tr>@endforelse</tbody></table></div></section></div>
<div class="col-xl-5"><section class="panel h-100"><div class="panel-head"><h2>Pipeline snapshot</h2><span class="muted">{{ $stats['overdue'] }} overdue follow-ups</span></div><div class="panel-body">@forelse($statusChart as $status=>$total)<div class="d-flex align-items-center gap-3 mb-3"><span class="small" style="width:110px">{{ $status }}</span><div class="progress flex-grow-1"><div class="progress-bar bg-success" style="width:{{ $stats['leads'] ? ($total/$stats['leads']*100) : 0 }}%"></div></div><strong class="small">{{$total}}</strong></div>@empty<p class="text-secondary">Your pipeline will appear after leads are collected.</p>@endforelse</div></section></div>
<div class="col-12"><section class="panel"><div class="panel-head"><h2>Recent high-intent opportunities</h2><a href="{{ route('leads.index',['lead_quality'=>'Hot']) }}" class="small">Explore hot leads</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Business</th><th>Location</th><th>Website</th><th>Rating</th><th>Score</th><th>Status</th></tr></thead><tbody>@forelse($hotLeads as $lead)<tr><td><a href="{{ route('leads.show',$lead) }}" class="business-name">{{$lead->business_name}}</a><div class="muted">{{$lead->business_category}}</div></td><td>{{$lead->city}}</td><td><span class="badge bg-danger-subtle text-danger">{{$lead->website_status}}</span></td><td>★ {{$lead->rating}} <span class="muted">({{$lead->total_reviews}})</span></td><td><span class="score">{{$lead->lead_score}}</span></td><td><span class="badge badge-soft">{{$lead->board_status}}</span></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-secondary">Qualified hot leads will surface here automatically.</td></tr>@endforelse</tbody></table></div></section></div>
</div>
@endsection
