@extends('layouts.app')
@section('title','Sales pipeline')
@section('eyebrow','Drag leads through your outreach workflow')
@section('content')
<section class="panel mb-4"><form class="panel-body filter-bar" method="get"><input class="form-control" name="search" value="{{request('search')}}" placeholder="Search this board"><select class="form-select" name="campaign_id"><option value="">All campaigns</option>@foreach($campaigns as $campaign)<option value="{{$campaign->id}}" @selected(request('campaign_id')==$campaign->id)>{{$campaign->title}}</option>@endforeach</select><input class="form-control" name="city" value="{{request('city')}}" placeholder="City"><input class="form-control" name="category" value="{{request('category')}}" placeholder="Category"><select class="form-select" name="lead_quality"><option value="">All quality</option>@foreach(['Hot','Warm','Cold'] as $v)<option @selected(request('lead_quality')===$v)>{{$v}}</option>@endforeach</select><button class="btn btn-brand">Apply</button></form></section>
<div class="board">@foreach($columns as $status=>$leads)<section class="board-column" data-status="{{$status}}"><div class="column-head"><span>{{$status}}</span><span class="column-count">{{$leads->count()}}</span></div><div class="card-list" data-status="{{$status}}">@foreach($leads as $lead)<article class="lead-card" data-id="{{$lead->id}}"><div class="d-flex justify-content-between gap-2"><div><h3>{{$lead->business_name}}</h3><div class="meta">{{$lead->business_category}} · {{$lead->city}}</div></div><strong class="text-success">{{$lead->lead_score}}</strong></div><div class="card-badges"><span class="badge quality-{{$lead->lead_quality}}">{{$lead->lead_quality}}</span>@unless($lead->has_website)<span class="badge bg-danger-subtle text-danger">No website</span>@endunless @if($lead->phone)<span class="badge bg-info-subtle text-info-emphasis">Has phone</span>@endif</div><div class="meta mb-2">★ {{$lead->rating ?: '—'}} · {{$lead->total_reviews}} reviews</div>@if($lead->follow_up_date)<div class="meta text-warning-emphasis mb-2"><i class="bi bi-calendar-event"></i> {{$lead->follow_up_date->format('d M Y')}}</div>@endif @if($lead->notes)<p class="meta mb-2">{{\Illuminate\Support\Str::limit($lead->notes,70)}}</p>@endif<div class="card-actions"><a href="{{route('leads.show',$lead)}}" title="Open"><i class="bi bi-eye"></i></a>@if($lead->google_maps_url)<a href="{{$lead->google_maps_url}}" target="_blank" title="Maps"><i class="bi bi-geo-alt"></i></a>@endif @if($lead->whatsapp_message_english)<button type="button" title="Copy message" onclick='navigator.clipboard.writeText(@json($lead->whatsapp_message_english))'><i class="bi bi-whatsapp"></i></button>@endif</div></article>@endforeach</div></section>@endforeach</div>
<div class="position-fixed bottom-0 end-0 p-3"><div id="boardToast" class="toast text-bg-success"><div class="toast-body">Lead status updated.</div></div></div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.2/Sortable.min.js"></script>
<script>
const token=document.querySelector('meta[name=csrf-token]').content, toast=new bootstrap.Toast('#boardToast');
document.querySelectorAll('.card-list').forEach(list=>new Sortable(list,{group:'leads',animation:160,ghostClass:'sortable-ghost',onEnd:async e=>{
 const card=e.item,status=e.to.dataset.status,old=e.from.dataset.status,oldIndex=e.oldIndex;
 try{const r=await fetch(`/leads/${card.dataset.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':token,'Accept':'application/json'},body:JSON.stringify({status,board_order:e.newIndex})});if(!r.ok)throw Error();document.querySelectorAll('.board-column').forEach(c=>c.querySelector('.column-count').textContent=c.querySelectorAll('.lead-card').length);toast.show();saveOrder()}catch(_){e.from.insertBefore(card,e.from.children[oldIndex]||null);alert('Status update failed. The card was returned to '+old+'.')}}}));
async function saveOrder(){const columns=[...document.querySelectorAll('.card-list')].map(c=>({status:c.dataset.status,leads:[...c.children].map((x,i)=>({id:+x.dataset.id,order:i}))}));await fetch('{{route('leads.board.reorder')}}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':token,'Accept':'application/json'},body:JSON.stringify({columns})})}
</script>
@endpush
