@extends('layouts.app')
@section('title','Lead intelligence')
@section('eyebrow','Qualified website opportunities')
@section('content')
<section class="panel mb-4"><form class="panel-body filter-bar lead-filter-form" method="get"><input class="form-control" name="search" value="{{request('search')}}" placeholder="Search business, phone or city"><select class="form-select auto-submit-filter" name="campaign_id"><option value="">All campaigns</option>@foreach($campaigns as $campaign)<option value="{{$campaign->id}}" @selected(request('campaign_id')==$campaign->id)>{{$campaign->title}}</option>@endforeach</select><select class="form-select auto-submit-filter" name="lead_quality"><option value="">All quality</option>@foreach(['Hot','Warm','Cold'] as $v)<option @selected(request('lead_quality')===$v)>{{$v}}</option>@endforeach</select><select class="form-select" name="status"><option value="">All statuses</option>@foreach(\App\Models\Lead::STATUSES as $v)<option @selected(request('status')===$v)>{{$v}}</option>@endforeach</select><select class="form-select" name="sort"><option value="score">Top score</option><option value="rating">Top rating</option><option value="reviews">Most reviews</option></select><button class="btn btn-brand"><i class="bi bi-funnel"></i> Filter</button><label class="small d-flex align-items-center gap-2"><input type="checkbox" name="without_website" value="1" @checked(request('without_website'))> No website only</label></form></section>
<section class="panel"><div class="panel-head"><div><h2>{{$leads->total()}} matched leads</h2><span class="muted">Public information from compliant sources</span></div><div class="d-flex gap-2"><a href="{{route('leads.board',request()->query())}}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-kanban"></i> Board</a><a href="{{route('exports.leads',request()->query())}}" class="btn btn-sm btn-outline-success"><i class="bi bi-file-earmark-excel"></i> Export Excel</a></div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Business</th><th>City</th><th>Phone</th><th>Website</th><th>Rating</th><th>Score</th><th>Quality</th><th>Status</th><th>Source</th><th></th></tr></thead><tbody>@forelse($leads as $lead)<tr><td><a href="{{route('leads.show',$lead)}}" class="business-name">{{$lead->business_name}}</a><div class="muted">{{$lead->business_category}}</div></td><td>{{$lead->city}}</td><td>{{$lead->formatted_phone ?: '—'}}</td><td>@include('partials.lead-website-link', ['lead' => $lead])</td><td>★ {{$lead->rating ?: '—'}} <span class="muted">({{$lead->total_reviews}})</span></td><td><span class="score">{{$lead->lead_score}}</span></td><td><span class="badge quality-{{$lead->lead_quality}}">{{$lead->lead_quality}}</span></td><td><span class="badge badge-soft">{{$lead->board_status}}</span></td><td class="muted">{{$lead->source_name}}</td><td><div class="dropdown"><button class="btn btn-sm btn-light" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{route('leads.show',$lead)}}">View details</a></li>@if($lead->google_maps_url)<li><a class="dropdown-item" target="_blank" href="{{$lead->google_maps_url}}">Open Google Maps</a></li>@endif @if($lead->facebook_url)<li><a class="dropdown-item" target="_blank" rel="noopener" href="{{$lead->facebook_url}}"><i class="bi bi-facebook me-2"></i>Facebook</a></li>@endif @if($lead->instagram_url)<li><a class="dropdown-item" target="_blank" rel="noopener" href="{{$lead->instagram_url}}"><i class="bi bi-instagram me-2"></i>Instagram</a></li>@endif @if($lead->linkedin_url)<li><a class="dropdown-item" target="_blank" rel="noopener" href="{{$lead->linkedin_url}}"><i class="bi bi-linkedin me-2"></i>LinkedIn</a></li>@endif @if($lead->whatsapp_message_english)<li><button class="dropdown-item" onclick='navigator.clipboard.writeText(@json($lead->whatsapp_message_english))'>Copy WhatsApp message</button></li>@endif</ul></div></td></tr>@empty<tr><td colspan="10" class="text-center py-5 text-secondary">No leads match these filters.</td></tr>@endforelse</tbody></table></div><div class="panel-body">{{$leads->links()}}</div></section>
@endsection

@push('scripts')
<script>
document.querySelectorAll('.auto-submit-filter').forEach((select) => {
    select.addEventListener('change', () => select.form.requestSubmit());
});
</script>
@endpush