@extends('layouts.app')
@section('title',$lead->business_name)
@section('eyebrow','Lead workspace · '.$lead->city)
@section('content')
<div class="d-flex flex-wrap gap-2 mb-4"><span class="badge quality-{{$lead->lead_quality}} fs-6">{{$lead->lead_quality}} · {{$lead->lead_score}}</span><span class="badge bg-danger-subtle text-danger fs-6">{{$lead->website_status}}</span><span class="badge badge-soft fs-6">{{$lead->board_status}}</span>@if($lead->google_maps_url)<a class="btn btn-sm btn-outline-secondary ms-auto" target="_blank" href="{{$lead->google_maps_url}}"><i class="bi bi-geo-alt"></i> Open Maps</a>@endif<form method="post" action="{{route('leads.ai',$lead)}}">@csrf<button class="btn btn-sm btn-brand"><i class="bi bi-stars"></i> Generate AI pitch</button></form></div>
<div class="detail-grid"><div><section class="panel mb-4"><div class="panel-head"><h2>Business opportunity</h2></div><div class="panel-body"><div class="row g-4"><div class="col-md-6"><p class="muted mb-1">Category</p><strong>{{$lead->business_category}}</strong></div><div class="col-md-6"><p class="muted mb-1">Location</p><strong>{{$lead->city}}, {{$lead->province}}</strong></div><div class="col-md-6"><p class="muted mb-1">Phone / WhatsApp</p><strong>{{$lead->formatted_phone ?: 'Not listed'}}</strong></div><div class="col-md-6"><p class="muted mb-1">Rating & reviews</p><strong>★ {{$lead->rating ?: '—'}} · {{$lead->total_reviews}} reviews</strong></div><div class="col-12"><p class="muted mb-1">Address</p><strong>{{$lead->address ?: 'Not available'}}</strong></div><div class="col-12"><p class="muted mb-1">Why this lead matches</p><p class="mb-0">{{$lead->match_reason ?: 'Run AI analysis for a richer qualification explanation.'}}</p></div><div class="col-12"><p class="muted mb-1">Suggested offer</p><p class="mb-0">{{$lead->suggested_offer}}</p></div></div></div></section>
<section class="panel mb-4"><div class="panel-head"><h2>Outreach kit</h2></div><div class="panel-body"><h3 class="h6">WhatsApp · English</h3><div class="message-box mb-2">{{$lead->whatsapp_message_english ?: 'Generate an AI pitch to create a personalized message.'}}</div>@if($lead->whatsapp_message_english)<button class="btn btn-sm btn-outline-secondary mb-4" onclick='navigator.clipboard.writeText(@json($lead->whatsapp_message_english))'>Copy message</button>@endif<h3 class="h6">WhatsApp · Localized</h3><div class="message-box mb-2">{{$lead->whatsapp_message_roman_urdu ?: 'A localized message will appear after AI analysis.'}}</div>@if($lead->whatsapp_message_roman_urdu)<button class="btn btn-sm btn-outline-secondary mb-4" onclick='navigator.clipboard.writeText(@json($lead->whatsapp_message_roman_urdu))'>Copy message</button>@endif<h3 class="h6">Email</h3><div class="message-box"><strong>{{$lead->email_subject}}</strong><br>{{$lead->email_body ?: 'Email copy will appear after AI analysis.'}}</div></div></section>
<section class="panel"><div class="panel-head"><h2>Activity timeline</h2></div><div class="panel-body timeline">@forelse($lead->activities as $activity)<div class="timeline-item"><strong class="small">{{$activity->description}}</strong><div class="muted">{{$activity->created_at->diffForHumans()}}</div></div>@empty<p class="text-secondary">No activity recorded yet.</p>@endforelse</div></section></div>
<div><section class="panel mb-4"><div class="panel-head"><h2>Move lead</h2></div><div class="panel-body"><select id="statusSelect" class="form-select">@foreach(\App\Models\Lead::STATUSES as $status)<option @selected($lead->board_status===$status)>{{$status}}</option>@endforeach</select><button id="statusButton" class="btn btn-brand w-100 mt-2">Update status</button></div></section>
<section class="panel mb-4"><div class="panel-head"><h2>Add note</h2></div><form class="panel-body" method="post" action="{{route('leads.notes.store',$lead)}}">@csrf<textarea class="form-control mb-3" name="note" rows="3" required placeholder="Conversation context, objection or next step"></textarea><button class="btn btn-outline-secondary w-100">Save note</button></form><div class="px-3 pb-3">@foreach($lead->leadNotes->take(4) as $note)<div class="border-top py-3 small">{{$note->note}}<div class="muted mt-1">{{$note->created_at->diffForHumans()}}</div></div>@endforeach</div></section>
<section class="panel"><div class="panel-head"><h2>Schedule follow-up</h2></div><form class="panel-body" method="post" action="{{route('leads.followups.store',$lead)}}">@csrf<input class="form-control mb-2" type="date" name="follow_up_date" required><input class="form-control mb-2" type="time" name="follow_up_time"><select class="form-select mb-2" name="method">@foreach(['WhatsApp','Call','Email','Visit','Other'] as $method)<option>{{$method}}</option>@endforeach</select><textarea class="form-control mb-3" name="note" rows="2" required placeholder="Purpose of follow-up"></textarea><button class="btn btn-brand w-100">Schedule</button></form></section></div></div>
@endsection
@push('scripts')<script>document.getElementById('statusButton').onclick=async()=>{const r=await fetch('{{route('leads.status',$lead)}}',{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({status:document.getElementById('statusSelect').value})});if(r.ok)location.reload();else alert('Could not update status.');}</script>@endpush
